// Generated by CoffeeScript 1.6.3
var BufferHelper, http, iconv, saver, stock;

http = require("http");

iconv = require('iconv-lite');

BufferHelper = require('bufferhelper');

stock = {};

/*

	stock.fetchIncrease 获取沪深股市的涨幅榜，
		- num：每次取的数目
		- page: 取第几页的数据
*/


stock.fetchIncrease = function(num, index) {
  var options, req;
  if (num == null) {
    num = 40;
  }
  if (index == null) {
    index = 1;
  }
  options = {
    hostname: 'vip.stock.finance.sina.com.cn',
    port: 80,
    path: "/quotes_service/api/json_v2.php/Market_Center.getHQNodeData?page=" + index + "&num=" + num + "&sort=changepercent&asc=0&node=hs_a&_s_r_a=init",
    method: "GET"
  };
  req = http.request(options, function(res) {
    var bufferHelper;
    bufferHelper = new BufferHelper();
    console.log("[ connected ]");
    res.on('data', function(chunk) {
      return bufferHelper.concat(chunk);
    });
    return res.on('end', function() {
      var data, retString;
      retString = iconv.decode(bufferHelper.toBuffer(), 'GB2312');
      data = eval("" + retString);
      return console.log(saver(data));
    });
  });
  return req.end();
};

/*
*/


saver = function(data) {
  var count, item, _i, _len;
  count = 0;
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    item = data[_i];
    if (stock.isTradingLimit(item)) {
      count++;
    } else {
      console.log(item.name);
      return counts;
    }
  }
  return count;
};

/*
	判断是否为涨停
*/


stock.isTradingLimit = function(stock) {
  var currentPrice, tradingLimit;
  if (stock.settlement) {
    currentPrice = (stock.trade - 0).toFixed(2);
    tradingLimit = (stock.settlement * 1.1).toFixed(2);
    return tradingLimit === currentPrice;
  } else {
    return false;
  }
};

stock.fetchIncrease(40, 2);
